# Generated by Django 4.2.20 on 2025-04-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_aggregatereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="aggregate_report",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="api.aggregatereport",
            ),
        ),
    ]
