# Generated by Django 4.2.20 on 2025-04-03 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0057_report_aggregate_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="aggregate_report",
        ),
        migrations.AddField(
            model_name="aggregatereport",
            name="report",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aggregate_report",
                to="api.report",
            ),
        ),
    ]
